name: GitHub Actions
on: [push]
jobs:
  Pages:
    runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: [3.8 ]
    steps:
      - run:  python --version
      - run:  pip install poetry
      - run:  poetry install
