name: GitHub Actions
on: [push]
jobs:
  Pages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8 ]
    steps:
      - name: Install dependencies
        run:  |
          python --version
          pip install poetry

